# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr.shape, arr.ndim, arr.dtype, arr.size, type(arr)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr2.size, type(arr3)

((1, 3, 3), 3, dtype('int32'), 6, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [7]:
# Create an array of shape (10, 2) with only ones
ones_1 = np.ones((10,2))
ones_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_1 = np.zeros((7,2,3))
zeros_1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
array_4 = np.arange(0,100,3)
array_4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_5 = np.random.randint(10,size=(7,2))
array_5

array([[1, 0],
       [8, 7],
       [4, 0],
       [7, 1],
       [6, 2],
       [0, 2],
       [7, 3]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_array = np.random.random(size=(3,5))
rand_array

array([[0.48106077, 0.00568041, 0.92343071, 0.56893632, 0.84127544],
       [0.9136328 , 0.84329136, 0.97076193, 0.31353004, 0.70631028],
       [0.25211295, 0.78920943, 0.82943115, 0.1984584 , 0.58743571]])

In [12]:
# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
array_6 = np.random.randint(0,10,size=(4,6))
array_6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

array_7 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
array_7, np.unique(array_7)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [14]:
# Find the 0'th index of the latest array you created
array_7[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
array_7[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
array_7[:2,:2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_8 = np.random.randint(0,10,size=(3,5))
arr_ones = np.ones((3,5))
array_8, arr_ones

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
# Add the two arrays together
array_8 + arr_ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
array_9 = np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together
arr_ones + array_9

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
Answer: can transpose new array

In [21]:
# Create another array of ones of shape (3, 5)
array_10 = np.ones((3,5))
array_10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
array_10 - array_8

array([[-5., -6., -1.,  1., -2.],
       [ 0., -6., -2.,  0., -4.],
       [-4., -8., -2., -4.,  0.]])

In [23]:
# Multiply the ones array with the latest array
array_9*array_10.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Take the latest array to the power of 2 using '**'
array_8**2, array_10**2

(array([[36, 49,  4,  0,  9],
        [ 1, 49,  9,  1, 25],
        [25, 81,  9, 25,  1]], dtype=int32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [25]:
# Do the same thing with np.square()
np.square(array_8), np.square(array_10)

(array([[36, 49,  4,  0,  9],
        [ 1, 49,  9,  1, 25],
        [25, 81,  9, 25,  1]], dtype=int32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [26]:
# Find the mean of the latest array using np.mean()
array_8.mean()

3.8666666666666667

In [27]:
# Find the maximum of the latest array using np.max()
array_8.max()

9

In [28]:
# Find the minimum of the latest array using np.min()
array_8.min()

0

In [29]:
# Find the standard deviation of the latest array
array_8.std()

2.578543947441829

In [30]:
# Find the variance of the latest array
array_8.var()

6.648888888888889

In [31]:
# Reshape the latest array to (3, 5, 1)
array_8.reshape((3,5,1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [32]:
# Transpose the latest array
array_8.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_11 = np.random.randint(0,10,size=(3,3))
array_12 = np.random.randint(0,10,size=(3,2))
array_11, array_12

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [34]:
# Perform a dot product on the two newest arrays you created
array_11.dot(array_12)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_13 = np.random.randint(0,10,size=(4,3))
array_14 = np.random.randint(0,10,size=(4,3))
array_13, array_14

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]]),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [36]:
# Perform a dot product on the two newest arrays you created
array_13.dot(array_14)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array_13.T.dot(array_14)


array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_15 = np.random.randint(0,10,size=(3,3))
array_16 = np.random.randint(0,10,size=(3,3))
array_15, array_16

(array([[6, 6, 7],
        [4, 2, 7],
        [5, 2, 0]]),
 array([[2, 4, 2],
        [0, 4, 9],
        [6, 6, 8]]))

In [39]:
# Compare the two arrays with '>'
array_15 > array_16

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='
array_15 >= array_16

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [41]:
# Find which elements of the first array are greater than 7
array_15 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [42]:
# Which parts of each array are equal? (try using '==')
array_15 == array_16

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [43]:
# Sort one of the arrays you just created in ascending order
array_15.sort(axis=1)
array_15

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5]])

In [44]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_15)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [45]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_15)

2

In [46]:
# Find the index with the minimum value in one of the arrays you've created
array_15.argmin()

6

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
array_15.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
array_15.argmin(axis=0)

array([2, 2, 2], dtype=int64)

In [49]:
# Create an array of normally distributed random numbers
array_17 = np.random.standard_normal((3,3))
array_17

array([[-0.61487576,  0.33289244, -1.38071702],
       [-0.28080629, -0.05981726,  0.96117377],
       [ 1.79428084,  0.58068954,  0.29765045]])

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array_18 = np.linspace(0,100,11)
array_18

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on Indexing/broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.